---
- hosts: web
  vars:
    http_port: 8080
    max_clients: 200
  remote_user: root
  tasks:
  - name: write the Java file
    template:
      src: ../target/react-fullstack-boilerplate-0.0.1-SNAPSHOT.jar
      dest: /home/alexforrestf/react-fullstack-boilerplate-0.0.1-SNAPSHOT.jar


