---
- hosts: web
  vars:
    http_port: 8080
    max_clients: 200
  remote_user: root
  tasks:
  - name: Write the Java file
    copy:
      src: ../target/react-fullstack-boilerplate-0.0.1-SNAPSHOT.jar
      dest: /home/alexforrestf/react-fullstack-boilerplate-0.0.1-SNAPSHOT.jar
    copy:
      src: supervisor.conf
      dest: /home/alexforrestf/supervisor.conf
  - name: (Re-)start the Java app
    supervisorctl:
      name: web
      state: restarted
      config: /home/alexforrestf/supervisor.conf